### ISSUE TITLE
Failing tests after recent commits

### ISSUE THREAD

**Issue by pat-s** [giscience-fsu/sperrorest#64]
@alexanderbrenning 

Some tests are failing after your recent commits. Would you have time to take a look?
Haven't taken a closer look yet (i.e. not sure if the test needs an update or the code).

https://github.com/giscience-fsu/sperrorest/runs/2485059020?check_suite_focus=true#step:15:96

(I am getting a notification daily for failing tests)

**Comment by alexanderbrenning** [comment]
Will look into it, should have checked the tests earlier; they need updating as there is an intended change to the internal handling of is_factor_prediction.

**Comment by alexanderbrenning** [comment]
Tests successful, closing issue.
