### ISSUE TITLE
Why is my result different from the example

### ISSUE THREAD

**Issue by phoenix-hy** [giscience-fsu/sperrorest#69]
Hello. First of all, Thank you so much for providing this package.
why my result in summary() is different from your example? my result don't have informtion like 'test_accuracy' and others. below are my codes.

``` r
library(rpart)
my_pred <- function(object, newdata) {
  pred1 <- predict(object, newdata=newdata)
  return (pred1)
}
future::plan(future.callr::callr, workers = 8)
non_scv <- sperrorest(fo,
                      data=data,
                      # coords=c('x','y'),
                      model_fun = rpart,
                      pred_fun = my_pred,
                      smp_fun = partition_cv,
                      smp_args = list(repetition=5 ,nfold=5),
                      mode_rep = 'sequential',
                      benchmark = TRUE, progress = 2,
)
summary(non_scv$error_rep)

```
But my output of summary() is not the same as the example from https://giscience-fsu.github.io/sperrorest/articles/spatial-modeling-use-case.html#ref-Pena2015.
Below is my result.
``` r
                      mean           sd        median          IQR
train_bias    2.273590e-19 5.375055e-18 -1.105073e-18 1.006920e-17
train_stddev  3.813609e-01 1.451281e-03  3.815055e-01 1.367855e-03
train_rmse    3.813514e-01 1.451244e-03  3.814959e-01 1.367821e-03
train_mad     2.810597e-01 2.593613e-02  2.725330e-01 2.473029e-02
train_median  1.325048e-01 1.025792e-02  1.305085e-01 1.008746e-02
train_iqr     3.446188e-01 1.123347e-02  3.509491e-01 1.637009e-02
train_count   2.000000e+04 0.000000e+00  2.000000e+04 0.000000e+00
test_bias    -4.383089e-04 1.057138e-03 -5.173791e-04 1.637201e-03
test_stddev   3.911263e-01 1.887174e-03  3.907905e-01 2.780909e-03
test_rmse     3.910886e-01 1.886764e-03  3.907526e-01 2.783169e-03
test_mad      2.914394e-01 2.476715e-02  2.943194e-01 5.381832e-03
test_median   1.354437e-01 1.397563e-02  1.305085e-01 1.681859e-02
test_iqr      3.494311e-01 8.262000e-03  3.509491e-01 1.258119e-02
test_count    5.000000e+03 0.000000e+00  5.000000e+03 0.000000e+00
```
and below is result of example.
``` r
##                    mean      sd   median     IQR
## train_error    0.00e+00 0.00000 0.00e+00 0.00000
## train_accuracy 1.00e+00 0.00000 1.00e+00 0.00000
## train_events   4.69e+03 0.00000 4.69e+03 0.00000
## train_count    3.09e+04 0.00000 3.09e+04 0.00000
## test_error     8.84e-02 0.00867 9.08e-02 0.00843
## test_accuracy  9.12e-01 0.00867 9.09e-01 0.00843
## test_events    1.17e+03 0.00000 1.17e+03 0.00000
## test_count     7.71e+03 0.00000 7.71e+03 0.00000
```

**Comment by pat-s** [comment]
Hi,

thanks for posting your issue here.
Please provide a [reproducible example](https://stackoverflow.com/questions/5963269/how-to-make-a-great-r-reproducible-example), preferably using the [reprex](https://github.com/tidyverse/reprex) package.
Otherwise we cannot infer what you did. Please also avoid posting screenshots, thanks!

**Comment by phoenix-hy** [comment]
@pat-s  Sorry, I re-edited my question.

**Comment by pat-s** [comment]
Thanks, your code is still not self-contained and cannot be run. Also it is good practice not to include parallelism unless it is relevant to the issue. Could you please revise the code again?

**Comment by phoenix-hy** [comment]
@pat-s  Thanks for your patience, I think I've figured out the reason. When my dependent variable is numeric like 0 and 1, the result is what I was before. But when my dependent variable is set to character, the result is the same as your example. So thanks again, I'll close this issue.

**Comment by pat-s** [comment]
Great! Yeah with a reprex this would have been easier to spot :) 

I assumed this but I am first emphasizing the need for a (simple) reproducible example - often this helps to spot issues while creating it without even having to open an issue :)
